services:
  mysql-image:
    image: mysql:9.0
    container_name: mysql-image
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: image_db
    ports:
      - "3312:3306"
    networks:
      - msa-network

  image-service:
    build:
      context: ../
      dockerfile: image-service/Dockerfile
    container_name: image-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-image:3306/image_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_ROOT_PASSWORD}
      - GATEWAY_SHARED_SECRET=${GATEWAY_SHARED_SECRET}
      - SERVER_PORT=8086
      - MANAGEMENT_ENDPOINTS_WEB_BASE_PATH=/images/actuator
    depends_on:
      - mysql-image
    networks:
      - msa-network

networks:
  msa-network:
    name: onmeet-network
    external: true
