// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/me/profile": {
            "delete": {
                "description": "현재 인증된 사용자가 업로드한 모든 프로필 카테고리 파일을 S3 및 DB에서 삭제합니다.\nS3 삭제 실패 시 해당 파일의 DB 삭제를 건너뛰어 고아(orphan) 레코드를 방지합니다.\n일부 파일 삭제 실패 시에도 500을 반환하며, 성공한 파일은 삭제됩니다.",
                "tags": [
                    "file"
                ],
                "summary": "내 프로필 이미지 삭제",
                "responses": {
                    "204": {
                        "description": "삭제 성공 (응답 본문 없음)"
                    },
                    "401": {
                        "description": "FILE_008: X-User-Id 헤더가 없어 사용자를 식별할 수 없는 경우",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "FILE_014: X-Gateway-Secret 헤더 누락 또는 불일치",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "FILE_009: S3 또는 DB 삭제 중 일부 또는 전체 실패",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profile/default": {
            "post": {
                "description": "이름 첫 글자와 배경색을 기반으로 SVG 프로필 이미지를 생성하고 S3에 저장합니다.\ncolor를 비워두면 서버에서 미리 정의된 고대비 색상 팔레트 중 하나를 랜덤 선택합니다.\n생성된 SVG는 category=profile로 저장됩니다.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "기본 프로필 이미지 생성",
                "parameters": [
                    {
                        "description": "프로필 생성 요청",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.GenerateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "생성된 프로필 이미지 메타데이터",
                        "schema": {
                            "$ref": "#/definitions/model.FileMetadata"
                        }
                    },
                    "400": {
                        "description": "FILE_010: 요청 JSON 파싱 실패 (잘못된 형식)",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "FILE_014: X-Gateway-Secret 헤더 누락 또는 불일치",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "FILE_011: SVG S3 업로드 또는 DB 저장 실패",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/render/{fileId}": {
            "get": {
                "description": "파일 ID로 S3에서 실제 파일 바이너리를 가져와 반환합니다.\n1MB 미만의 파일은 서버 인메모리 캐시(TTL 1시간)에 저장되어 반복 요청 시 S3 호출 없이 응답합니다.\n응답 Content-Type은 파일의 실제 타입(image/jpeg, application/pdf 등)으로 동적 결정됩니다.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "file"
                ],
                "summary": "파일 렌더링 (다운로드)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "파일 ID (양의 정수)",
                        "name": "fileId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "파일 바이너리 데이터 (Cache-Control: public, max-age=3600)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "FILE_012: fileId가 유효한 양의 정수가 아닌 경우",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "FILE_014: X-Gateway-Secret 헤더 누락 또는 불일치",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "FILE_013: 파일 메타데이터 없음 또는 S3 다운로드 실패 | FILE_033: DB에서 파일을 찾을 수 없음",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "FILE_034: S3 GetObject 오류 | FILE_035: 파일 내용 읽기 오류",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "description": "멀티파트 폼으로 하나 이상의 파일을 S3에 업로드합니다.\n업로드된 파일의 메타데이터(URL, 크기, 타입 등)가 PostgreSQL에 저장됩니다.\ncategory, ownerType, ownerId를 지정하지 않으면 기본값(USER / 업로더 ID)이 사용됩니다.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "파일 업로드",
                "parameters": [
                    {
                        "type": "file",
                        "description": "업로드할 파일 (복수 가능)",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "파일 카테고리 (예: TEAM_PROFILE, MEETING_SUMMARY)",
                        "name": "category",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "소유자 타입 (USER | TEAM | COMPANY). 기본값: USER",
                        "name": "ownerType",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "소유자 ID. 미입력 시 업로더 ID 사용",
                        "name": "ownerId",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "업로드된 파일 메타데이터 목록",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.FileMetadata"
                            }
                        }
                    },
                    "400": {
                        "description": "FILE_001: 멀티파트 폼 데이터 파싱 실패 (Content-Type이 multipart/form-data가 아닌 경우)",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "FILE_014: X-Gateway-Secret 헤더 누락 또는 불일치",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "FILE_002: S3 업로드 또는 DB 저장 실패",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/upload-async": {
            "post": {
                "description": "파일을 백그라운드 고루틴으로 비동기 처리하고 즉시 202를 반환합니다.\n실제 S3 업로드 완료 후 callbackTopic으로 Kafka 이벤트가 발행됩니다.\n업로드 실패 시 클라이언트에 별도 에러 응답이 없으며 서버 로그에만 기록됩니다.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "파일 비동기 업로드",
                "parameters": [
                    {
                        "type": "file",
                        "description": "업로드할 파일 (복수 가능)",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "파일 카테고리",
                        "name": "category",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "소유자 타입 (USER | TEAM | COMPANY)",
                        "name": "ownerType",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "소유자 ID",
                        "name": "ownerId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "업로드 완료 Kafka 토픽. 기본값: file-upload-events",
                        "name": "callbackTopic",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "요청 추적을 위한 Correlation ID",
                        "name": "correlationId",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "202": {
                        "description": "비동기 업로드 시작 확인 (message, fileCount)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "FILE_003: 멀티파트 폼 데이터 파싱 실패",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "FILE_014: X-Gateway-Secret 헤더 누락 또는 불일치",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{fileId}": {
            "get": {
                "description": "파일 ID로 DB에 저장된 파일 메타데이터(URL, 크기, 카테고리 등)를 조회합니다.\n실제 파일 바이너리가 아닌 메타데이터만 반환합니다. 파일 내용은 /render/{fileId}를 사용하세요.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "파일 메타데이터 조회",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "파일 ID (양의 정수)",
                        "name": "fileId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "파일 메타데이터",
                        "schema": {
                            "$ref": "#/definitions/model.FileMetadata"
                        }
                    },
                    "400": {
                        "description": "FILE_004: fileId가 유효한 양의 정수가 아닌 경우",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "FILE_014: X-Gateway-Secret 헤더 누락 또는 불일치",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "FILE_005: 해당 ID의 파일이 DB에 존재하지 않는 경우 | FILE_042: DB 레코드 없음",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "FILE_041: DB 연결 오류 등 내부 서버 에러",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "파일 ID로 파일을 삭제합니다. S3에서 즉시 삭제(Hard Delete)되고 DB는 Soft Delete 처리됩니다.\n삭제 권한: MANAGER 또는 ADMIN 역할 보유자만 가능합니다.\n회사 파일(ownerType=COMPANY)은 동일 회사 관리자만, 개인 파일은 동일 회사 소속 관리자만 삭제 가능합니다.",
                "tags": [
                    "file"
                ],
                "summary": "파일 삭제",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "파일 ID (양의 정수)",
                        "name": "fileId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "삭제 성공 (응답 본문 없음)"
                    },
                    "400": {
                        "description": "FILE_006: fileId가 유효한 양의 정수가 아닌 경우",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "FILE_014: 게이트웨이 시크릿 오류 | FILE_020: MANAGER/ADMIN 권한 없음 | FILE_021: 다른 회사 파일 접근 불가",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "FILE_042: 삭제 대상 파일이 DB에 존재하지 않는 경우",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "FILE_007: S3 삭제 또는 DB 삭제 실패 | FILE_019: auth-service 권한 조회 실패",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.GenerateProfileRequest": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string",
                    "example": "#FF5733"
                },
                "name": {
                    "type": "string",
                    "example": "홍길동"
                },
                "ownerId": {
                    "type": "string",
                    "example": "123"
                },
                "ownerType": {
                    "type": "string",
                    "example": "USER"
                }
            }
        },
        "model.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "FILE_001"
                },
                "message": {
                    "type": "string",
                    "example": "멀티파트 폼 데이터 파싱에 실패했습니다"
                },
                "status": {
                    "type": "integer",
                    "example": 400
                },
                "timestamp": {
                    "type": "integer",
                    "example": 1234567890123
                }
            }
        },
        "model.FileMetadata": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "example": "TEAM_PROFILE"
                },
                "contentType": {
                    "type": "string",
                    "example": "image/jpeg"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2024-03-10T09:00:00Z"
                },
                "extraInfo": {
                    "description": "datatypes.JSON은 PostgreSQL의 jsonb 타입을 지원하기 위한 특수 타입입니다.",
                    "type": "object"
                },
                "fileName": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000.jpg"
                },
                "fileSize": {
                    "type": "integer",
                    "example": 204800
                },
                "id": {
                    "description": "백틱(` + "`" + `) 안에 있는 것은 'Struct Tag'라고 하며, GORM(ORM) 설정이나 JSON 변환 설정을 담습니다.\ngorm:\"primaryKey\"는 JPA의 @Id와 같고, json:\"id\"는 Jackson의 @JsonProperty(\"id\")와 같습니다.",
                    "type": "integer",
                    "example": 1
                },
                "originalFileName": {
                    "type": "string",
                    "example": "photo.jpg"
                },
                "ownerId": {
                    "type": "string",
                    "example": "123"
                },
                "ownerType": {
                    "type": "string",
                    "example": "USER"
                },
                "s3Url": {
                    "type": "string",
                    "example": "https://cdn.onmeet.cloud/USER/123/TEAM_PROFILE/550e8400.jpg"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2024-03-10T09:00:00Z"
                },
                "uploaderId": {
                    "description": "*int64처럼 포인터를 쓰는 이유는 DB의 NULL 값을 허용하기 위해서입니다. (Java의 클래스 타입 Integer와 유사)",
                    "type": "integer",
                    "example": 42
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api.onmeet.cloud",
	BasePath:         "/file/v1",
	Schemes:          []string{},
	Title:            "OnMeet File Service API",
	Description:      "OnMeet 파일 관리 서비스입니다. S3(또는 MinIO) 기반의 파일 업로드/다운로드, 프로필 이미지 생성/삭제를 담당합니다.\n\n## 인증\n모든 엔드포인트는 `X-Gateway-Secret` 헤더를 통한 게이트웨이 시크릿 검증이 필요합니다.\n사용자 정보는 `X-User-Id`, `X-User-Roles` 헤더로 전달됩니다 (게이트웨이에서 JWT 검증 후 주입).\n\n## 에러 응답 형식\n모든 에러는 다음 JSON 형식으로 반환됩니다:\n`{\"code\": \"FILE_001\", \"status\": 400, \"message\": \"에러 메시지\", \"timestamp\": 1710000000000}`\n\n## 공통 에러\n- `FILE_014` (403): X-Gateway-Secret 헤더가 없거나 일치하지 않는 경우 (모든 엔드포인트)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
