include:
  - gateway-service/docker-compose.yml
  - auth-service/docker-compose.yml
  - ai-service/docker-compose.yml
  - video-service/docker-compose.yml
  - chat-service/docker-compose.yml
  - notification-service/docker-compose.yml
  - file-service/docker-compose.yml
  - kafka/docker-compose.yml

networks:
  msa-network:
    name: onmeet-network
