### (1) 히스토리 조회
GET http://localhost:8080/api/chats/history?meetRoomId=1&size=10

###

### (2) 메시지 보내기(TEXT)
POST http://localhost:8080/api/chats
Content-Type: application/json

{
  "meetRoomId": 1,
  "messageType": "TEXT",
  "content": "http client test",
  "attachmentJson": null
}
