spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  mail:
    from: ${GMAIL_USERNAME:${GMAIL_USERNAME}}
  company-verification:
    base-url: ${COMPANY_VERIFICATION_BASE_URL:https://onmeeteven.netlify.app/verify-company}
