package main

import (
	"log"

	"com.onmeet.file/internal/client"
	"com.onmeet.file/internal/config"
	"com.onmeet.file/internal/handler"
	"com.onmeet.file/internal/middleware"
	"com.onmeet.file/internal/model"
	"com.onmeet.file/internal/repository"
	"com.onmeet.file/internal/service"
	"github.com/gin-gonic/gin"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"

	_ "com.onmeet.file/docs" // docs is generated by Swag CLI
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title           OnMeet File Service API
// @version         1.0
// @description     OnMeet 파일 관리 서비스입니다. S3(또는 MinIO) 기반의 파일 업로드/다운로드, 프로필 이미지 생성/삭제를 담당합니다.
// @description
// @description     ## 인증
// @description     모든 엔드포인트는 `X-Gateway-Secret` 헤더를 통한 게이트웨이 시크릿 검증이 필요합니다.
// @description     사용자 정보는 `X-User-Id`, `X-User-Roles` 헤더로 전달됩니다 (게이트웨이에서 JWT 검증 후 주입).
// @description
// @description     ## 에러 응답 형식
// @description     모든 에러는 다음 JSON 형식으로 반환됩니다:
// @description     `{"code": "FILE_001", "status": 400, "message": "에러 메시지", "timestamp": 1710000000000}`
// @description
// @description     ## 공통 에러
// @description     - `FILE_014` (403): X-Gateway-Secret 헤더가 없거나 일치하지 않는 경우 (모든 엔드포인트)

// @host            api.onmeet.cloud
// @BasePath        /file/v1

// main 함수는 프로그램의 시작점입니다. Java의 public static void main과 같습니다.
func main() {
	// 1. 설정 로드
	cfg := config.LoadConfig()

	// 2. 데이터베이스 연결 (GORM 이용)
	// postgres.Open은 연결 정보를 담은 드라이버를 생성합니다.
	db, err := gorm.Open(postgres.Open(cfg.PostgresURL), &gorm.Config{})
	if err != nil {
		// log.Fatal은 메시지를 출력하고 프로그램을 즉시 종료합니다.
		log.Fatal("Failed to connect to database:", err)
	}

	// 3. 테이블 자동 생성 (마이그레이션)
	// JPA의 hibernate.ddl-auto: update와 유사한 기능입니다.
	_ = db.AutoMigrate(&model.FileMetadata{})

	// 4. 의존성 주입 (Dependency Injection)
	// Go는 Spring처럼 자동으로 빈을 관리하지 않기 때문에, 아래처럼 직접 생성해서 연결해줍니다.
	repo := repository.NewPostgresFileRepository(db)
	s3Svc, err := service.NewS3Service(cfg)
	if err != nil {
		log.Fatal("Failed to setup S3 service:", err)
	}

	auth := client.NewAuthClient(cfg)
	ep := service.NewKafkaEventProducer(cfg)
	svc := service.NewFileService(repo, s3Svc, ep, auth, cfg)
	h := handler.NewFileHandler(svc)

	// 5. 웹 서버(Router) 설정
	// gin.Default()는 로깅과 패닉 복구 미들웨어가 포함된 기본 엔진을 생성합니다.
	r := gin.Default()

	// 6. 전역 미들웨어 설정
	r.Use(CORSMiddleware())
	r.Use(middleware.ErrorHandlerMiddleware())

	// 7. 라우팅 설정 (API 엔드포인트)
	// Public Group (Swagger, Health Check)
	publicGroup := r.Group("/file")
	{
		// Swagger UI (ginSwagger가 자동으로 doc.json 제공)
		publicGroup.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	}

	// Health Check (Public, without /v1)
	r.GET("/file/actuator/health", func(c *gin.Context) {
		c.JSON(200, gin.H{"status": "UP"})
	})

	// Protected Group (API with /v1)
	protectedGroup := r.Group("/file/v1")
	protectedGroup.Use(middleware.SecurityMiddleware(cfg))
	{
		protectedGroup.POST("/upload", h.Upload)
		protectedGroup.POST("/upload-async", h.UploadAsync)
		protectedGroup.POST("/profile/default", h.GenerateProfileImage)
		protectedGroup.GET("/render/:fileId", h.RenderFile)
		protectedGroup.GET("/:fileId", h.GetFileInfo)
		protectedGroup.DELETE("/:fileId", h.DeleteFile)
		protectedGroup.DELETE("/me/profile", h.DeleteMyProfile)
	}

	// 8. 서버 실행
	log.Printf("File Service (PostgreSQL) starting on port %s...", cfg.Port)
	if err := r.Run(":" + cfg.Port); err != nil {
		log.Fatal("Failed to run server:", err)
	}
}

func CORSMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Writer.Header().Set("Access-Control-Allow-Origin", "http://localhost:8080")
		c.Writer.Header().Set("Access-Control-Allow-Credentials", "true")
		c.Writer.Header().Set("Access-Control-Allow-Headers", "Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, accept, origin, Cache-Control, X-Requested-With")
		c.Writer.Header().Set("Access-Control-Allow-Methods", "POST, OPTIONS, GET, PUT, DELETE")

		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(204)
			return
		}

		c.Next()
	}
}
