package main

import (
	"context"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"com.onmeet.file/internal/client"
	"com.onmeet.file/internal/config"
	"com.onmeet.file/internal/handler"
	"com.onmeet.file/internal/middleware"
	"com.onmeet.file/internal/model"
	"com.onmeet.file/internal/repository"
	"com.onmeet.file/internal/service"
	"github.com/gin-gonic/gin"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"

	_ "com.onmeet.file/docs" // docs is generated by Swag CLI
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title           OnMeet File Service API
// @version         1.0
// @description     OnMeet 파일 관리 서비스입니다. S3(또는 MinIO) 기반의 파일 업로드/다운로드, 프로필 이미지 생성/삭제를 담당합니다.
// @description
// @description     ## 인증
// @description     모든 엔드포인트는 `X-Gateway-Secret` 헤더를 통한 게이트웨이 시크릿 검증이 필요합니다.
// @description     사용자 정보는 `X-User-Id`, `X-User-Roles` 헤더로 전달됩니다 (게이트웨이에서 JWT 검증 후 주입).
// @description
// @description     ## 에러 응답 형식
// @description     모든 에러는 다음 JSON 형식으로 반환됩니다:
// @description     `{"code": "FILE_001", "status": 400, "message": "에러 메시지", "timestamp": 1710000000000}`
// @description
// @description     ## 공통 에러
// @description     - `FILE_014` (403): X-Gateway-Secret 헤더가 없거나 일치하지 않는 경우 (모든 엔드포인트)

// @host            api.onmeet.cloud
// @BasePath        /file/v1

func main() {
	// 1. 설정 로드
	cfg := config.LoadConfig()

	// 2. 보안: GATEWAY_SHARED_SECRET가 비어있으면 기동 거부
	if cfg.GatewaySharedSecret == "" {
		log.Fatal("GATEWAY_SHARED_SECRET environment variable must not be empty")
	}

	// 3. 데이터베이스 연결 (GORM 이용)
	db, err := gorm.Open(postgres.Open(cfg.PostgresURL), &gorm.Config{})
	if err != nil {
		log.Fatal("Failed to connect to database:", err)
	}

	// 4. PostgreSQL 커넥션 풀 설정
	sqlDB, err := db.DB()
	if err != nil {
		log.Fatal("Failed to get sql.DB from GORM:", err)
	}
	sqlDB.SetMaxOpenConns(25)
	sqlDB.SetMaxIdleConns(10)
	sqlDB.SetConnMaxLifetime(5 * time.Minute)

	// 5. 테이블 자동 생성 (마이그레이션) - 에러 처리 추가
	if err := db.AutoMigrate(&model.FileMetadata{}); err != nil {
		log.Fatal("Failed to run AutoMigrate:", err)
	}

	// 6. 의존성 주입
	repo := repository.NewPostgresFileRepository(db)
	s3Svc, err := service.NewS3Service(cfg)
	if err != nil {
		log.Fatal("Failed to setup S3 service:", err)
	}

	auth := client.NewAuthClient(cfg)
	ep := service.NewKafkaEventProducer(cfg)
	svc := service.NewFileService(repo, s3Svc, ep, auth, cfg)
	h := handler.NewFileHandler(svc)

	// 7. 웹 서버(Router) 설정
	r := gin.Default()

	// 8. 전역 미들웨어 설정
	r.Use(middleware.ErrorHandlerMiddleware())

	// 9. 라우팅 설정
	publicGroup := r.Group("/file")
	{
		publicGroup.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	}

	r.GET("/file/actuator/health", func(c *gin.Context) {
		c.JSON(200, gin.H{"status": "UP"})
	})

	protectedGroup := r.Group("/file/v1")
	protectedGroup.Use(middleware.SecurityMiddleware(cfg))
	{
		protectedGroup.POST("/upload", h.Upload)
		protectedGroup.POST("/upload-async", h.UploadAsync)
		protectedGroup.POST("/profile/default", h.GenerateProfileImage)
		protectedGroup.GET("/render/:fileId", h.RenderFile)
		protectedGroup.POST("/register-s3", h.RegisterS3File)
		protectedGroup.GET("/:fileId", h.GetFileInfo)
		protectedGroup.DELETE("/:fileId", h.DeleteFile)
		protectedGroup.DELETE("/me/profile", h.DeleteMyProfile)
	}

	// 10. Graceful Shutdown 설정
	srv := &http.Server{
		Addr:    ":" + cfg.Port,
		Handler: r,
	}

	go func() {
		log.Printf("File Service (PostgreSQL) starting on port %s...", cfg.Port)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatal("Failed to run server:", err)
		}
	}()

	// OS 시그널 대기 (SIGINT, SIGTERM)
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("Shutting down server...")

	// 5초 내 graceful shutdown
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if err := srv.Shutdown(ctx); err != nil {
		log.Printf("Server forced to shutdown: %v", err)
	}

	// Kafka writer 닫기
	if err := ep.Close(); err != nil {
		log.Printf("Kafka writer close error: %v", err)
	}

	log.Println("Server exited")
}

