services:
  mysql-chat:
    image: mysql:9.0
    container_name: mysql-chat
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_db
    ports:
      - "3310:3306"
    networks:
      - msa-network

  chat-service:
    build:
      context: ../
      dockerfile: chat-service/Dockerfile
    container_name: chat-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-chat:3306/chat_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - GATEWAY_SHARED_SECRET=my-super-secure-gateway-secret
    depends_on:
      - mysql-chat
    networks:
      - msa-network

networks:
  msa-network:
    name: onmeet-network
    external: true
