services:
  mysql-auth:
    image: mysql:9.0
    container_name: mysql-auth
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - msa-network

  auth-service:
    build:
      context: ../
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "${AUTH_SERVICE_PORT:-8081}:${AUTH_SERVICE_PORT:-8081}"
    environment:
      - SPRING_DATASOURCE_URL=${AUTH_DB_URL:-jdbc:mysql://mysql-auth:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_ROOT_PASSWORD}
      - GATEWAY_SHARED_SECRET=${GATEWAY_SHARED_SECRET}
      - AUTH_ENCRYPTION_KEY=${AUTH_ENCRYPTION_KEY}
      - SPRING_DATA_REDIS_HOST=${AUTH_REDIS_HOST:-redis-auth}
      - SERVER_PORT=${AUTH_SERVICE_PORT:-8081}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-kafka:29092}
    depends_on:
      mysql-auth:
        condition: service_healthy
      redis-auth:
        condition: service_started
      kafka:
        condition: service_healthy
    networks:
      - msa-network

  redis-auth:
    image: redis:alpine
    container_name: redis-auth
    ports:
      - "6379:6379"
    networks:
      - msa-network

networks:
  msa-network:
    name: onmeet-network
    external: true
