services:
  nginx:
    image: nginx:1.25.3-alpine
    container_name: onmeet-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    networks:
      - onmeet-network

  certbot:
    image: certbot/certbot:v2.7.4
    container_name: onmeet-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - onmeet-network

networks:
  onmeet-network:
    external: true
    name: onmeet-network
